version: "3.7"
services:
  apptest:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: testserver
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - testnetwork
  dbtest:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - ${DB_LOCAL_ACCES}:${DB_PORT}
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - testnetwork
  nginxtest:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - dbtest
      - apptest
    networks:
      - testnetwork
networks:
  testnetwork:
    driver: bridge
